apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fbinstance.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" . | nindent 4 }}
data:
  auth.json: |
    {{- include "fbinstance.authConfig" . | trim | nindent 4 }}
