{{- range .Values.engines }}
{{- $engine := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $engine.name }}-service
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" $ | nindent 4 }}
    firebolt/component: engine
    firebolt/engine: {{ $engine.name }}
spec:
  type: ClusterIP
  selector:
    {{- include "fbinstance.selectorLabels" $ | nindent 4 }}
    firebolt/engine: {{ $engine.name }}
  ports:
    {{- include "fbinstance.enginePorts" $ | nindent 4 }}
{{- end }}
