{{- range .Values.engines }}
{{- $engine := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fbinstance.fullname" $ }}-engine-{{ $engine.name }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" $ | nindent 4 }}
    firebolt/component: engine
    firebolt/engine: {{ $engine.name }}
data:
  config.yaml: |
    {{- include "fbinstance.engineConfig" (dict "root" $ "engine" $engine) | trim | nindent 4 }}
{{- end }}
