{{- if not .Values.postgresql.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fbinstance.fullname" . }}-metadata-postgres-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" . | nindent 4 }}
    firebolt/component: metadata-service
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
