apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fbinstance.fullname" . }}-metadata-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" . | nindent 4 }}
    firebolt/component: metadata-service
data:
  config.xml: |
    <?xml version="1.0"?>
    <config>
      <pensieve_lite>
        <host>{{ .Values.metadata.server.host }}</host>
        <port>{{ .Values.metadata.server.port }}</port>
        <server_threads>{{ .Values.metadata.server.threads }}</server_threads>
        <log_level>{{ .Values.metadata.server.log_level }}</log_level>
        <metadata_storage>
          <postgresql>
            {{- if .Values.postgresql.local_enabled }}
            <host>{{ include "fbinstance.fullname" . }}-metadata-pg</host>
            {{- else }}
            <host>{{ .Values.postgresql.host }}</host>
            {{- end }}
            <port>{{ .Values.postgresql.port }}</port>
            <database>{{ .Values.postgresql.database }}</database>
            <schema>{{ .Values.postgresql.schema }}</schema>

            <keepalive>
              <enabled>{{ .Values.postgresql.keepalive.enabled }}</enabled>
              <idle_sec>{{ .Values.postgresql.keepalive.idle_sec }}</idle_sec>
              <interval_sec>{{ .Values.postgresql.keepalive.interval_sec }}</interval_sec>
              <count>{{ .Values.postgresql.keepalive.count }}</count>
            </keepalive>
            <connect_timeout_sec>{{ .Values.postgresql.connect_timeout_sec }}</connect_timeout_sec>
          </postgresql>
          <garbage_collection>
            <enabled>true</enabled>
            <interval_seconds>3600</interval_seconds>
            <max_age_seconds>86400</max_age_seconds>
          </garbage_collection>
        </metadata_storage>
      </pensieve_lite>
    </config>
