{{- if not .Values.postgresql.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fbinstance.fullname" . }}-pensieve-postgres-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" . | nindent 4 }}
    firebolt/component: pensieve-dedicated
type: Opaque
data:
  {{- if .Values.postgresql.username }}
  username: {{ .Values.postgresql.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.password }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- end }}
{{- end }}
