{{- if .Values.postgresql.enabled }}
{{- /* Internal postgres: create credentials from bitnami auth values */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fbinstance.fullname" . }}-pensieve-postgres-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" . | nindent 4 }}
    firebolt/component: pensieve-dedicated
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- else if not .Values.metadata.postgresql.credentials.existingSecret }}
{{- /* External postgres without an existing secret: create from inline values */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fbinstance.fullname" . }}-pensieve-postgres-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fbinstance.labels" . | nindent 4 }}
    firebolt/component: pensieve-dedicated
type: Opaque
data:
  {{- if .Values.metadata.postgresql.credentials.username }}
  username: {{ .Values.metadata.postgresql.credentials.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.metadata.postgresql.credentials.password }}
  password: {{ .Values.metadata.postgresql.credentials.password | b64enc | quote }}
  {{- end }}
{{- end }}
